import { Employees } from "@/types/type";



export const mockEmployees: Employees = [
  {
    allInformationFilled: true,
    draftFlag: false,
    developer: "True",
    isConsultant: false,
    isDeveloper: true,
    biometricID: "BIO12345",
    employeeIdentifier: "EMP001",
    state: "Active",
    status: "Working",
    userId: "U001",

    bankData: {
      accountName: "Rajesh Kumar",
      accountNumber: "1234567890",
      bankIFSC: "HDFC0001234",
      branchName: "Salt Lake Branch",
    },

    basicData: {
      bloodGroup: "B+",
      companyId: "C001",
      confirmDate: "2023-05-01",
      discipline: "Software",
      dob: "1995-08-15",
      email: "rajesh.k@example.com",
      firstName: "Rajesh",
      middleName: "Kumar",
      lastName: "Singh",
      gender: "Male",
      grade: "G5",
      joiningDate: "2021-06-01",
      orgEmail: "rajesh.k@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "rajesh_profile.jpg",
      },
      reportingManager: "EMP010",
      resignationDate: "",
      role: "Developer",
    },

    contactData: {
      currGuardian: "Suresh Singh",
      currGuardianPhn: "9876543210",
      currRelation: "Father",
      currentAddr: "Kolkata, West Bengal",
      currentPin: "700091",
      currentState: "West Bengal",
      permGuardian: "Suresh Singh",
      permGuardianPhn: "9876543210",
      permRelation: "Father",
      permanentAddr: "Patna, Bihar",
      permanentPin: "800001",
      permanentState: "Bihar",
      phnNumber: "9123456780",
    },

    educationData: {
      ugDegreeName: "B.Tech CSE",
      ugDegreePassingYear: "2017",
      ugInstituteName: "IEM Kolkata",
      ugPercentage: "75%",
      pgDegreeName: null,
      pgDegreePassingYear: null,
      pgInstituteName: "",
      pgPercentage: "",
      xInstituteName: "St. Xavier’s School",
      xPassingYear: "2011",
      xPercentage: "88%",
      xiiInstituteName: "DAV Public School",
      xiiPassingYear: "2013",
      xiiPercentage: "85%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC101",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 250000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC102",
          resourceName: "x_marksheet.pdf",
          resourceSize: 150000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC103",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 200000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "1234-5678-9012",
      panNumber: "ABCDE1234F",
      passportNumber: "N1234567",
      voterNumber: "WB123456",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC201",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 150000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC202",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 50000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC203",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 60000,
          resourceType: "pdf",
        },
      },
    },

    rate: "50000",
  },

  {
    allInformationFilled: true,
    draftFlag: false,
    developer: "False",
    isConsultant: true,
    isDeveloper: false,
    biometricID: "BIO67890",
    employeeIdentifier: "EMP002",
    state: "Active",
    status: "Working",
    userId: "U002",

    bankData: {
      accountName: "Priya Sharma",
      accountNumber: "9876543210",
      bankIFSC: "SBI0004567",
      branchName: "Andheri Branch",
    },

    basicData: {
      bloodGroup: "O+",
      companyId: "C002",
      confirmDate: "2022-01-01",
      discipline: "Consulting",
      dob: "1992-03-22",
      email: "priya.s@example.com",
      firstName: "Priya",
      middleName: "",
      lastName: "Sharma",
      gender: "Female",
      grade: "G6",
      joiningDate: "2020-09-10",
      orgEmail: "priya.s@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "priya_profile.jpg",
      },
      reportingManager: "EMP011",
      resignationDate: "",
      role: "Consultant",
    },

    contactData: {
      currGuardian: "Rakesh Sharma",
      currGuardianPhn: "9812345678",
      currRelation: "Father",
      currentAddr: "Mumbai, Maharashtra",
      currentPin: "400001",
      currentState: "Maharashtra",
      permGuardian: "Rakesh Sharma",
      permGuardianPhn: "9812345678",
      permRelation: "Father",
      permanentAddr: "Jaipur, Rajasthan",
      permanentPin: "302001",
      permanentState: "Rajasthan",
      phnNumber: "9988776655",
    },

    educationData: {
      ugDegreeName: "B.Com",
      ugDegreePassingYear: "2013",
      ugInstituteName: "Mumbai University",
      ugPercentage: "70%",
      pgDegreeName: "MBA",
      pgDegreePassingYear: "2016",
      pgInstituteName: "NMIMS",
      pgPercentage: "78%",
      xInstituteName: "Modern School",
      xPassingYear: "2008",
      xPercentage: "89%",
      xiiInstituteName: "Sophia School",
      xiiPassingYear: "2010",
      xiiPercentage: "87%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC301",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 200000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC302",
          resourceName: "x_marksheet.pdf",
          resourceSize: 120000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC303",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 180000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "2345-6789-0123",
      panNumber: "PQRSX5678Y",
      passportNumber: "M7654321",
      voterNumber: "MH654321",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC401",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 140000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC402",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 60000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC403",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 75000,
          resourceType: "pdf",
        },
      },
    },

    rate: "70000",
  },

  {
    allInformationFilled: false,
    draftFlag: true,
    developer: "True",
    isConsultant: false,
    isDeveloper: true,
    biometricID: "BIO11122",
    employeeIdentifier: "EMP003",
    state: "Inactive",
    status: "On Hold",
    userId: "U003",

    bankData: {
      accountName: "Amit Das",
      accountNumber: "111122223333",
      bankIFSC: "ICIC0007890",
      branchName: "Salt Lake Sector V",
    },

    basicData: {
      bloodGroup: "A+",
      companyId: "C003",
      confirmDate: "",
      discipline: "Testing",
      dob: "1998-11-02",
      email: "amit.d@example.com",
      firstName: "Amit",
      middleName: "",
      lastName: "Das",
      gender: "Male",
      grade: "G3",
      joiningDate: "2023-02-15",
      orgEmail: "amit.d@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "amit_profile.png",
      },
      reportingManager: "EMP001",
      resignationDate: "",
      role: "QA Tester",
    },

    contactData: {
      currGuardian: "Pradip Das",
      currGuardianPhn: "9898989898",
      currRelation: "Father",
      currentAddr: "Bidhannagar, Kolkata",
      currentPin: "700054",
      currentState: "West Bengal",
      permGuardian: "Pradip Das",
      permGuardianPhn: "9898989898",
      permRelation: "Father",
      permanentAddr: "Durgapur, West Bengal",
      permanentPin: "713201",
      permanentState: "West Bengal",
      phnNumber: "9000001111",
    },

    educationData: {
      ugDegreeName: "B.Sc IT",
      ugDegreePassingYear: "2019",
      ugInstituteName: "Techno India",
      ugPercentage: "72%",
      pgDegreeName: null,
      pgDegreePassingYear: null,
      pgInstituteName: "",
      pgPercentage: "",
      xInstituteName: "Holy Cross School",
      xPassingYear: "2013",
      xPercentage: "84%",
      xiiInstituteName: "Holy Cross School",
      xiiPassingYear: "2015",
      xiiPercentage: "81%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC501",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 180000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC502",
          resourceName: "x_marksheet.pdf",
          resourceSize: 100000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC503",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 150000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "3456-7890-1234",
      panNumber: "LMNOP2345Z",
      passportNumber: "",
      voterNumber: "WB789012",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC601",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 120000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC602",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 50000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC603",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 70000,
          resourceType: "pdf",
        },
      },
    },

    rate: "30000",
  },

  // -------------------- NEW EMPLOYEES --------------------
  {
    allInformationFilled: true,
    draftFlag: false,
    developer: "True",
    isConsultant: false,
    isDeveloper: true,
    biometricID: "BIO22233",
    employeeIdentifier: "EMP004",
    state: "Active",
    status: "Working",
    userId: "U004",

    bankData: {
      accountName: "Sneha Roy",
      accountNumber: "222233334444",
      bankIFSC: "AXIS0004567",
      branchName: "Park Street Branch",
    },

    basicData: {
      bloodGroup: "AB+",
      companyId: "C004",
      confirmDate: "2022-07-15",
      discipline: "Frontend Development",
      dob: "1996-12-10",
      email: "sneha.roy@example.com",
      firstName: "Sneha",
      middleName: "",
      lastName: "Roy",
      gender: "Female",
      grade: "G4",
      joiningDate: "2021-09-20",
      orgEmail: "sneha.roy@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "sneha_profile.png",
      },
      reportingManager: "EMP002",
      resignationDate: "",
      role: "Frontend Developer",
    },

    contactData: {
      currGuardian: "Anil Roy",
      currGuardianPhn: "9876001234",
      currRelation: "Father",
      currentAddr: "Bangalore, Karnataka",
      currentPin: "560001",
      currentState: "Karnataka",
      permGuardian: "Anil Roy",
      permGuardianPhn: "9876001234",
      permRelation: "Father",
      permanentAddr: "Kolkata, West Bengal",
      permanentPin: "700007",
      permanentState: "West Bengal",
      phnNumber: "9012345678",
    },

    educationData: {
      ugDegreeName: "B.Tech IT",
      ugDegreePassingYear: "2018",
      ugInstituteName: "VIT Vellore",
      ugPercentage: "77%",
      pgDegreeName: null,
      pgDegreePassingYear: null,
      pgInstituteName: "",
      pgPercentage: "",
      xInstituteName: "Loreto Convent",
      xPassingYear: "2012",
      xPercentage: "90%",
      xiiInstituteName: "Loreto Convent",
      xiiPassingYear: "2014",
      xiiPercentage: "87%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC701",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 200000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC702",
          resourceName: "x_marksheet.pdf",
          resourceSize: 110000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC703",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 170000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "4567-8901-2345",
      panNumber: "QWERT1234X",
      passportNumber: "P1239876",
      voterNumber: "KA456789",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC801",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 140000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC802",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 60000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC803",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 80000,
          resourceType: "pdf",
        },
      },
    },

    rate: "55000",
  },

  {
    allInformationFilled: true,
    draftFlag: false,
    developer: "False",
    isConsultant: true,
    isDeveloper: false,
    biometricID: "BIO33344",
    employeeIdentifier: "EMP005",
    state: "Active",
    status: "Working",
    userId: "U005",

    bankData: {
      accountName: "Arjun Mehta",
      accountNumber: "333344445555",
      bankIFSC: "YESB0006789",
      branchName: "Connaught Place Branch",
    },

    basicData: {
      bloodGroup: "B-",
      companyId: "C005",
      confirmDate: "2021-03-10",
      discipline: "Business Analysis",
      dob: "1990-05-30",
      email: "arjun.mehta@example.com",
      firstName: "Arjun",
      middleName: "",
      lastName: "Mehta",
      gender: "Male",
      grade: "G7",
      joiningDate: "2019-11-25",
      orgEmail: "arjun.mehta@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "arjun_profile.jpg",
      },
      reportingManager: "EMP004",
      resignationDate: "",
      role: "Business Consultant",
    },

    contactData: {
      currGuardian: "Ravi Mehta",
      currGuardianPhn: "9888001122",
      currRelation: "Father",
      currentAddr: "Delhi, India",
      currentPin: "110001",
      currentState: "Delhi",
      permGuardian: "Ravi Mehta",
      permGuardianPhn: "9888001122",
      permRelation: "Father",
      permanentAddr: "Ahmedabad, Gujarat",
      permanentPin: "380001",
      permanentState: "Gujarat",
      phnNumber: "9876543211",
    },

    educationData: {
      ugDegreeName: "BBA",
      ugDegreePassingYear: "2011",
      ugInstituteName: "Delhi University",
      ugPercentage: "72%",
      pgDegreeName: "MBA",
      pgDegreePassingYear: "2013",
      pgInstituteName: "IIM Ahmedabad",
      pgPercentage: "82%",
      xInstituteName: "St. Columba’s School",
      xPassingYear: "2006",
      xPercentage: "85%",
      xiiInstituteName: "St. Columba’s School",
      xiiPassingYear: "2008",
      xiiPercentage: "88%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC901",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 210000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC902",
          resourceName: "x_marksheet.pdf",
          resourceSize: 100000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC903",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 160000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "5678-9012-3456",
      panNumber: "ZXCVB6789Y",
      passportNumber: "L9876543",
      voterNumber: "DL987654",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC1001",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 150000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC1002",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 70000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC1003",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 90000,
          resourceType: "pdf",
        },
      },
    },

    rate: "90000",
  },

  {
    allInformationFilled: false,
    draftFlag: true,
    developer: "True",
    isConsultant: false,
    isDeveloper: true,
    biometricID: "BIO44455",
    employeeIdentifier: "EMP006",
    state: "Inactive",
    status: "Resigned",
    userId: "U006",

    bankData: {
      accountName: "Neha Gupta",
      accountNumber: "444455556666",
      bankIFSC: "PNB0009876",
      branchName: "Lucknow Branch",
    },

    basicData: {
      bloodGroup: "O-",
      companyId: "C006",
      confirmDate: "",
      discipline: "Backend Development",
      dob: "1994-08-08",
      email: "neha.g@example.com",
      firstName: "Neha",
      middleName: "",
      lastName: "Gupta",
      gender: "Female",
      grade: "G5",
      joiningDate: "2020-07-01",
      orgEmail: "neha.g@company.com",
      profilePicture: {
        originalPicDetails: {},
        landScapePicDetails: {},
        portaitPicDetails: {},
        iconPicDetails: {},
        originalImageName: "neha_profile.jpg",
      },
      reportingManager: "EMP005",
      resignationDate: "2024-03-01",
      role: "Backend Developer",
    },

    contactData: {
      currGuardian: "Sunil Gupta",
      currGuardianPhn: "9777002233",
      currRelation: "Father",
      currentAddr: "Lucknow, Uttar Pradesh",
      currentPin: "226001",
      currentState: "Uttar Pradesh",
      permGuardian: "Sunil Gupta",
      permGuardianPhn: "9777002233",
      permRelation: "Father",
      permanentAddr: "Varanasi, Uttar Pradesh",
      permanentPin: "221001",
      permanentState: "Uttar Pradesh",
      phnNumber: "9123456700",
    },

    educationData: {
      ugDegreeName: "B.Tech CSE",
      ugDegreePassingYear: "2016",
      ugInstituteName: "AKTU",
      ugPercentage: "74%",
      pgDegreeName: null,
      pgDegreePassingYear: null,
      pgInstituteName: "",
      pgPercentage: "",
      xInstituteName: "City Montessori School",
      xPassingYear: "2010",
      xPercentage: "92%",
      xiiInstituteName: "City Montessori School",
      xiiPassingYear: "2012",
      xiiPercentage: "89%",

      educationDocuments: {
        ugMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC1101",
          resourceName: "ug_marksheet.pdf",
          resourceSize: 220000,
          resourceType: "pdf",
        },
        xMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC1102",
          resourceName: "x_marksheet.pdf",
          resourceSize: 115000,
          resourceType: "pdf",
        },
        xiiMarksheetFile: {
          inputControl: "file",
          resourceId: "DOC1103",
          resourceName: "xii_marksheet.pdf",
          resourceSize: 175000,
          resourceType: "pdf",
        },
      },
    },

    personalIdData: {
      aadhaarNumber: "6789-0123-4567",
      panNumber: "ASDFG2345P",
      passportNumber: "",
      voterNumber: "UP123456",
      personalDocuments: {
        aadhaarFile: {
          resourceId: "DOC1201",
          inputControl: "file",
          resourceName: "aadhaar.pdf",
          resourceSize: 130000,
          resourceType: "pdf",
        },
        panFile: {
          resourceId: "DOC1202",
          inputControl: "file",
          resourceName: "pan.pdf",
          resourceSize: 55000,
          resourceType: "pdf",
        },
        voterFile: {
          resourceId: "DOC1203",
          inputControl: "file",
          resourceName: "voter.pdf",
          resourceSize: 65000,
          resourceType: "pdf",
        },
      },
    },

    rate: "60000",
  },
];
